/**
 * Migration 013: Execution Kernel v4 tables.
 *
 * Adds tables for derived execution profiles, admission decisions,
 * deadline watchdog runs, and state authority violations.
 */

import type { Kysely } from "kysely";
import { sql } from "kysely";
import type { Database } from "../types.js";

export async function up(db: Kysely<Database>): Promise<void> {
	// Derived execution profiles — generated by ExecutionProfileDeriver
	await db.schema
		.createTable("derived_execution_profiles")
		.addColumn("id", "uuid", (col) => col.primaryKey().defaultTo(sql`gen_random_uuid()`))
		.addColumn("plan_execution_id", "uuid", (col) => col.notNull())
		.addColumn("intent", "jsonb", (col) => col.notNull())
		.addColumn("derived_profile", "jsonb", (col) => col.notNull())
		.addColumn("deriver_version", "varchar(64)", (col) => col.notNull())
		.addColumn("created_at", "timestamptz", (col) => col.notNull().defaultTo(sql`now()`))
		.execute();

	await db.schema
		.createIndex("idx_derived_profiles_plan_exec")
		.on("derived_execution_profiles")
		.column("plan_execution_id")
		.execute();

	// Admission decisions — recorded by AdmissionGate for every entrypoint check
	await db.schema
		.createTable("admission_decisions")
		.addColumn("id", "uuid", (col) => col.primaryKey().defaultTo(sql`gen_random_uuid()`))
		.addColumn("plan_execution_id", "uuid")
		.addColumn("request_type", "varchar(128)", (col) => col.notNull())
		.addColumn("decision", "varchar(64)", (col) => col.notNull())
		.addColumn("reasons", "jsonb", (col) => col.notNull().defaultTo(sql`'[]'::jsonb`))
		.addColumn("derived_profile", "jsonb")
		.addColumn("created_at", "timestamptz", (col) => col.notNull().defaultTo(sql`now()`))
		.execute();

	await db.schema
		.createIndex("idx_admission_decisions_plan_exec")
		.on("admission_decisions")
		.column("plan_execution_id")
		.execute();

	await db.schema
		.createIndex("idx_admission_decisions_decision")
		.on("admission_decisions")
		.column("decision")
		.execute();

	// Deadline watchdog runs — records of each scan cycle
	await db.schema
		.createTable("deadline_watchdog_runs")
		.addColumn("id", "uuid", (col) => col.primaryKey().defaultTo(sql`gen_random_uuid()`))
		.addColumn("started_at", "timestamptz", (col) => col.notNull())
		.addColumn("completed_at", "timestamptz")
		.addColumn("expired_attempt_count", "integer", (col) => col.notNull().defaultTo(0))
		.addColumn("emitted_event_count", "integer", (col) => col.notNull().defaultTo(0))
		.addColumn("error", "text")
		.execute();

	// State authority violations — records of any detected direct state mutations
	await db.schema
		.createTable("state_authority_violations")
		.addColumn("id", "uuid", (col) => col.primaryKey().defaultTo(sql`gen_random_uuid()`))
		.addColumn("source", "varchar(255)", (col) => col.notNull())
		.addColumn("plan_execution_id", "uuid")
		.addColumn("workspace_execution_id", "uuid")
		.addColumn("attempt_id", "uuid")
		.addColumn("violation_type", "varchar(128)", (col) => col.notNull())
		.addColumn("payload", "jsonb", (col) => col.notNull().defaultTo(sql`'{}'::jsonb`))
		.addColumn("created_at", "timestamptz", (col) => col.notNull().defaultTo(sql`now()`))
		.execute();

	await db.schema.createIndex("idx_sav_source").on("state_authority_violations").column("source").execute();

	await db.schema
		.createIndex("idx_sav_violation_type")
		.on("state_authority_violations")
		.column("violation_type")
		.execute();
}

export async function down(db: Kysely<Database>): Promise<void> {
	await db.schema.dropTable("state_authority_violations").ifExists().execute();
	await db.schema.dropTable("deadline_watchdog_runs").ifExists().execute();
	await db.schema.dropTable("admission_decisions").ifExists().execute();
	await db.schema.dropTable("derived_execution_profiles").ifExists().execute();
}
