/**
 * Proposal Candidate Generator — V5.05
 *
 * Synthesizes proposal candidates from scanner findings (hotspots, risky
 * diffs, failure correlations, stale plan areas).
 *
 * Proposal candidates are concrete improvement suggestions generated by
 * combining multiple scanner signals. Each candidate is backed by evidence
 * and can be escalated to the proposals system for review.
 *
 * Rules:
 * - A hotspot with high change count + failure correlation → refactoring proposal
 * - A risky diff with large changes → review/break-down proposal
 * - A stale plan area → revive/close proposal
 * - Repeated failure patterns in the same area → investigation proposal
 *
 * This module is purely analytical — it generates candidates in-memory
 * and does not mutate any state. Candidates are returned to the caller
 * for optional escalation.
 *
 * @packageDocumentation
 */

import type { EvidenceRef } from "../evidence/types.js";
import type { FailureCorrelation, Hotspot, ProposalCandidate, RiskyDiff, StalePlanArea } from "./types.js";
import { scoreToPriority } from "./types.js";

// =========================================================================
// Proposal Candidate Generator
// =========================================================================

/**
 * Generates proposal candidates by combining scanner findings.
 *
 * Takes the output of hotspot, risky diff, failure correlation, and
 * stale area scanners and synthesizes actionable proposal candidates.
 */
export class ProposalCandidateGenerator {
	/** Maximum number of candidates to generate per category. */
	private readonly maxPerCategory: number;

	constructor(maxPerCategory: number = 5) {
		this.maxPerCategory = maxPerCategory;
	}

	// =======================================================================
	// Public API
	// =======================================================================

	/**
	 * Generate proposal candidates from scanner findings.
	 *
	 * @param hotspots - Detected hotspots
	 * @param riskyDiffs - Detected risky diffs
	 * @param failureCorrelations - Detected failure correlations
	 * @param stalePlanAreas - Detected stale plan areas
	 * @returns Array of proposal candidates sorted by priority then confidence
	 */
	generate(
		hotspots: Hotspot[],
		riskyDiffs: RiskyDiff[],
		failureCorrelations: FailureCorrelation[],
		stalePlanAreas: StalePlanArea[],
	): ProposalCandidate[] {
		const candidates: ProposalCandidate[] = [];

		// 1. Hotspot + failure correlation → refactoring candidates
		candidates.push(...this.generateRefactoringCandidates(hotspots, failureCorrelations));

		// 2. Hotspot alone → attention candidates
		candidates.push(...this.generateHotspotAttentionCandidates(hotspots));

		// 3. Risky diffs → review/break-down candidates
		candidates.push(...this.generateDiffReviewCandidates(riskyDiffs));

		// 4. Failure correlations alone → investigation candidates
		candidates.push(...this.generateInvestigationCandidates(failureCorrelations));

		// 5. Stale plan areas → revive/close candidates
		candidates.push(...this.generateStalePlanCandidates(stalePlanAreas));

		// Sort: high first, then by confidence descending
		const priorityOrder = { high: 0, medium: 1, low: 2 };
		candidates.sort((a, b) => {
			const aOrder = priorityOrder[a.priority];
			const bOrder = priorityOrder[b.priority];
			if (aOrder !== bOrder) return aOrder - bOrder;
			return b.confidence - a.confidence;
		});

		return candidates;
	}

	// =======================================================================
	// Candidate Generation Strategies
	// =======================================================================

	/**
	 * Generate refactoring candidates from hotspots with failure correlation.
	 *
	 * When a file is both a hotspot (high change frequency) and has correlated
	 * failures, it is a strong candidate for refactoring.
	 */
	private generateRefactoringCandidates(
		hotspots: Hotspot[],
		failureCorrelations: FailureCorrelation[],
	): ProposalCandidate[] {
		const candidates: ProposalCandidate[] = [];
		const correlationMap = new Map<string, FailureCorrelation>();

		for (const fc of failureCorrelations) {
			correlationMap.set(fc.path, fc);
		}

		let count = 0;

		for (const hotspot of hotspots) {
			if (count >= this.maxPerCategory) break;

			const correlation = correlationMap.get(hotspot.path);
			if (!correlation) continue;

			const evidence: EvidenceRef[] = [
				...hotspot.evidence,
				...correlation.evidence,
				{
					type: "observation",
					id: `refactor-candidate:${hotspot.path}`,
					label: `Refactoring candidate for ${hotspot.path}`,
					description: `Generated from hotspot (${hotspot.changeCount} changes) and failure correlation (${correlation.failureCount} failures)`,
					timestamp: new Date().toISOString(),
					confidence: Math.min(0.5 + hotspot.changeCount * 0.05 + correlation.failureCount * 0.1, 0.95),
				},
			];

			const confidence = Math.min(
				0.4 + (hotspot.changeCount / 20) * 0.3 + (correlation.failureCount / 10) * 0.3,
				0.95,
			);

			candidates.push({
				title: `Refactor ${hotspot.path}`,
				description: `'${hotspot.path}' is a high-change area (${hotspot.changeCount} changes) with ${correlation.failureCount} correlated failure(s). This combination suggests the area may benefit from refactoring to reduce churn and improve stability. Top error pattern: ${correlation.errorPatterns[0] || "unknown"}.`,
				priority: scoreToPriority(confidence),
				suggestedAction: `Review ${hotspot.path} for refactoring opportunities. Consider splitting into smaller modules, adding tests, or simplifying the logic. Error pattern "${correlation.errorPatterns[0] || "unknown"}" should be investigated as part of the refactoring.`,
				evidence,
				confidence: Math.round(confidence * 100) / 100,
				summary: `Refactor '${hotspot.path}': ${hotspot.changeCount} changes, ${correlation.failureCount} failure(s)`,
				triggeredBy: ["hotspot", "failure_correlation"],
				metadata: {
					changeCount: hotspot.changeCount,
					failureCount: correlation.failureCount,
					topErrors: correlation.errorPatterns,
				},
			});

			count++;
		}

		return candidates;
	}

	/**
	 * Generate attention candidates from hotspots without failure correlation.
	 *
	 * High-churn areas that don't yet have correlated failures still warrant
	 * attention as they may indicate code that is becoming complex.
	 */
	private generateHotspotAttentionCandidates(hotspots: Hotspot[]): ProposalCandidate[] {
		const candidates: ProposalCandidate[] = [];
		let count = 0;

		for (const hotspot of hotspots) {
			if (count >= this.maxPerCategory) break;

			// Skip hotspots that already have a refactoring candidate
			// (those with failure correlation are handled above)
			if (hotspot.changeCount < 10) continue;

			const confidence = Math.min(0.3 + (hotspot.changeCount / 20) * 0.2, 0.7);

			const evidence: EvidenceRef[] = [
				...hotspot.evidence,
				{
					type: "observation",
					id: `hotspot-attention:${hotspot.path}`,
					label: `High-churn attention candidate for ${hotspot.path}`,
					description: `Generated from hotspot with ${hotspot.changeCount} changes`,
					timestamp: new Date().toISOString(),
					confidence: 0.6,
				},
			];

			candidates.push({
				title: `Monitor high-churn area: ${hotspot.path}`,
				description: `'${hotspot.path}' has experienced ${hotspot.changeCount} changes recently. While no failures are yet correlated, high change frequency can indicate code that is becoming complex or unstable.`,
				priority: scoreToPriority(confidence),
				suggestedAction: `Review the change history of ${hotspot.path} to understand why it changes frequently. Consider if the area needs architectural attention or if changes can be reduced through better abstractions.`,
				evidence,
				confidence: Math.round(confidence * 100) / 100,
				summary: `Monitor '${hotspot.path}': ${hotspot.changeCount} changes (high churn)`,
				triggeredBy: ["hotspot"],
				metadata: {
					changeCount: hotspot.changeCount,
					contributorCount: hotspot.contributorCount,
				},
			});

			count++;
		}

		return candidates;
	}

	/**
	 * Generate review/break-down candidates from risky diffs.
	 *
	 * Large diffs that touch multiple areas or have high churn should be
	 * reviewed and potentially broken into smaller, more focused changes.
	 */
	private generateDiffReviewCandidates(riskyDiffs: RiskyDiff[]): ProposalCandidate[] {
		const candidates: ProposalCandidate[] = [];
		let count = 0;

		for (const diff of riskyDiffs) {
			if (count >= this.maxPerCategory) break;

			// Focus on high-risk diffs
			if (diff.riskScore < 0.6) continue;

			const confidence = Math.min(0.3 + diff.riskScore * 0.5, 0.9);

			const evidence: EvidenceRef[] = [
				...diff.evidence,
				{
					type: "observation",
					id: `diff-review:${diff.commitHash}`,
					label: `Large diff review candidate: ${diff.commitHash.slice(0, 8)}`,
					description: `Generated from risky diff with ${diff.totalChanges} changes across ${diff.filesChanged.length} file(s), risk score ${(diff.riskScore * 100).toFixed(0)}%`,
					timestamp: new Date().toISOString(),
					confidence: 0.7,
				},
			];

			const commitRef =
				diff.commitHash === "uncommitted" ? "uncommitted changes" : `commit ${diff.commitHash.slice(0, 8)}`;

			candidates.push({
				title: `Review large change: ${commitRef}`,
				description: `${commitRef} introduces ${diff.totalChanges} changes across ${diff.filesChanged.length} file(s) with a risk score of ${(diff.riskScore * 100).toFixed(0)}%. ${diff.touchesMultipleAreas ? "It touches multiple functional areas, which may indicate scope creep." : ""} Consider breaking this into smaller, focused changes.`,
				priority: scoreToPriority(confidence),
				suggestedAction: `Review ${commitRef}. If it touches multiple concerns, break it into separate commits. If it is already committed, consider filing a cleanup proposal.`,
				evidence,
				confidence: Math.round(confidence * 100) / 100,
				summary: `Large diff: ${diff.totalChanges} changes across ${diff.filesChanged.length} file(s)`,
				triggeredBy: ["risky_diff"],
				metadata: {
					commitHash: diff.commitHash,
					totalChanges: diff.totalChanges,
					fileCount: diff.filesChanged.length,
					riskScore: diff.riskScore,
					touchesMultipleAreas: diff.touchesMultipleAreas,
				},
			});

			count++;
		}

		return candidates;
	}

	/**
	 * Generate investigation candidates from failure correlations.
	 *
	 * Areas with repeated failures that are not already hotspots suggest
	 * a latent issue that needs investigation.
	 */
	private generateInvestigationCandidates(failureCorrelations: FailureCorrelation[]): ProposalCandidate[] {
		const candidates: ProposalCandidate[] = [];
		let count = 0;

		for (const fc of failureCorrelations) {
			if (count >= this.maxPerCategory) break;

			if (fc.failureCount < 3) continue;

			const confidence = Math.min(0.3 + (fc.failureCount / 10) * 0.4 + fc.correlationConfidence * 0.3, 0.95);

			const evidence: EvidenceRef[] = [
				...fc.evidence,
				{
					type: "observation",
					id: `investigate-candidate:${fc.path}`,
					label: `Investigation candidate for ${fc.path}`,
					description: `Generated from ${fc.failureCount} failure(s) with ${fc.errorPatterns.length} distinct error pattern(s)`,
					timestamp: new Date().toISOString(),
					confidence: fc.correlationConfidence,
				},
			];

			candidates.push({
				title: `Investigate failures in ${fc.path}`,
				description: `'${fc.path}' is correlated with ${fc.failureCount} failure(s) (confidence: ${(fc.correlationConfidence * 100).toFixed(0)}%). Error patterns: ${fc.errorPatterns.join(", ")}. This area may have latent bugs or instability that needs investigation.`,
				priority: scoreToPriority(confidence),
				suggestedAction: `Investigate the failure patterns in ${fc.path}. Review recent changes, add tests, and consider if the area needs hardening.`,
				evidence,
				confidence: Math.round(confidence * 100) / 100,
				summary: `Investigate '${fc.path}': ${fc.failureCount} failure(s), confidence ${(fc.correlationConfidence * 100).toFixed(0)}%`,
				triggeredBy: ["failure_correlation"],
				metadata: {
					failureCount: fc.failureCount,
					errorPatterns: fc.errorPatterns,
					correlationConfidence: fc.correlationConfidence,
				},
			});

			count++;
		}

		return candidates;
	}

	/**
	 * Generate revive/close candidates from stale plan areas.
	 *
	 * Plans that have not been touched recently should either be revived
	 * (picked up again) or formally closed.
	 */
	private generateStalePlanCandidates(stalePlanAreas: StalePlanArea[]): ProposalCandidate[] {
		const candidates: ProposalCandidate[] = [];
		let count = 0;

		for (const area of stalePlanAreas) {
			if (count >= this.maxPerCategory) break;

			const confidence = Math.min(0.3 + (area.daysSinceModification / 30) * 0.3, 0.8);

			const evidence: EvidenceRef[] = [
				...area.evidence,
				{
					type: "observation",
					id: `stale-plan:${area.path}`,
					label: `Stale plan candidate: ${area.planName || area.path}`,
					description: `Generated from plan untouched for ${area.daysSinceModification} day(s)`,
					timestamp: new Date().toISOString(),
					confidence: 0.7,
				},
			];

			const action =
				area.daysSinceModification > 30
					? `Consider closing "${area.planName || area.path}" — it has been untouched for ${area.daysSinceModification} day(s). If still relevant, assign ownership and set a deadline.`
					: `Review "${area.planName || area.path}" — it has been untouched for ${area.daysSinceModification} day(s). Decide whether to revive, defer, or close.`;

			candidates.push({
				title: `Address stale plan: ${area.planName || area.path}`,
				description: `Plan "${area.planName || area.path}" has not been modified in ${area.daysSinceModification} day(s) (status: ${area.status}). Stale plans can indicate stalled execution, unresolved blockers, or completed-but-not-closed work.`,
				priority: area.daysSinceModification > 30 ? "high" : "medium",
				suggestedAction: action,
				evidence,
				confidence: Math.round(confidence * 100) / 100,
				summary: `Stale plan "${area.planName || area.path}": ${area.daysSinceModification} day(s) untouched`,
				triggeredBy: ["stale_plan_area"],
				metadata: {
					daysSinceModification: area.daysSinceModification,
					status: area.status,
					planName: area.planName,
				},
			});

			count++;
		}

		return candidates;
	}
}

// =========================================================================
// Factory
// =========================================================================

/**
 * Create a ProposalCandidateGenerator instance.
 *
 * @param maxPerCategory - Maximum candidates per category (default: 5)
 * @returns A new ProposalCandidateGenerator
 */
export function createProposalCandidateGenerator(maxPerCategory?: number): ProposalCandidateGenerator {
	return new ProposalCandidateGenerator(maxPerCategory);
}
