/**
 * ExecutionProfileDeriver for v4 ExecutionKernel.
 *
 * AUTHORITATIVE derivation logic. All plan profile derivation MUST
 * route through this module. The core/execution-profile.ts module
 * delegates to this module to ensure a single derivation path.
 *
 * Converts human-authored intent into a derived execution profile.
 * The profile is read-only and generated by the system. It defines
 * required mechanisms such as worktree isolation, integration queue,
 * validation lanes, GitRunner queue, and event journal requirements.
 *
 * Human authors SHOULD NOT manually override derived profile fields.
 */

// =========================================================================
// Shared primitive types
//
// Defined locally to avoid circular dependency with core/execution-profile.ts
// which re-exports from this module. These are the canonical definitions.
// =========================================================================

export type IntentSafetyLevel = "relaxed" | "normal" | "strict";
export type IntentConflictRisk = "none" | "low" | "medium" | "high";
export type IntentExecutionEnvironmentMode = "trusted_local" | "local_sandbox" | "cloud_sandbox";

// =========================================================================
// Types
// =========================================================================

export interface ExecutionIntent {
	parallelism: number;
	safetyLevel: IntentSafetyLevel;
	conflictRisk: IntentConflictRisk;
	executionEnvironment: {
		mode: IntentExecutionEnvironmentMode;
	};
	deadlines?: Record<string, number>;
}

export interface DerivedExecutionProfile {
	/** Whether a separate git worktree is required for each workspace. */
	worktreeRequired: boolean;
	/** Whether the integration queue is required for serialized merges. */
	integrationQueueRequired: boolean;
	/** Whether the GitRunner queue is required for serialized repo mutations. */
	gitRunnerQueueRequired: boolean;
	/** Whether validation lanes are required. */
	validationLanesRequired: boolean;
	/** Maximum concurrent heavy validation commands. */
	heavyValidationMax: number;
	/** Maximum concurrent targeted validation commands. */
	targetedValidationMax: number;
	/** Whether an attempt event journal is required. */
	eventJournalRequired: boolean;
	/** Whether attempt-scoped artifacts are required. */
	attemptScopedArtifactsRequired: boolean;
	/** Whether writeSet drift detection is required. */
	writeSetDriftDetectionRequired: boolean;
	/** Whether writeSet drift blocks integration or just warns. */
	writeSetDriftBlockOnConflict: boolean;
	/** Whether the DeadlineWatchdog is required. */
	deadlineWatchdogRequired: boolean;
	/** Admission gate mode: "normal" or "strict". */
	admissionGateMode: "normal" | "strict";
	/** Whether explicit approval is required for execution. */
	explicitApprovalRequired: boolean;
	/** Whether JSON runtime fallback is forbidden. */
	jsonRuntimeFallbackForbidden: boolean;
	/** Required sandbox features. */
	sandboxRequirements: string[];
	/** Human-readable explanations for derived decisions. */
	explanations: string[];
	/** Deriver version. */
	deriverVersion: string;
}

// =========================================================================
// Derivation logic
// =========================================================================

/**
 * Derive an execution profile from human-authored intent.
 */
export function deriveExecutionProfile(intent: ExecutionIntent): DerivedExecutionProfile {
	const explanations: string[] = [];
	const p = intent.parallelism;
	const safety = intent.safetyLevel;
	const risk = intent.conflictRisk;
	const env = intent.executionEnvironment.mode;

	// Validate inputs
	if (p < 1 || p > 8) {
		throw new Error(`intent.parallelism must be between 1 and 8, got ${p}`);
	}
	if (safety === "relaxed" && p > 1) {
		throw new Error("relaxed safetyLevel is only allowed for parallelism <= 1");
	}

	const profile: DerivedExecutionProfile = {
		worktreeRequired: false,
		integrationQueueRequired: false,
		gitRunnerQueueRequired: true,
		validationLanesRequired: false,
		heavyValidationMax: 1,
		targetedValidationMax: 3,
		eventJournalRequired: false,
		attemptScopedArtifactsRequired: false,
		writeSetDriftDetectionRequired: true,
		writeSetDriftBlockOnConflict: true,
		deadlineWatchdogRequired: true,
		admissionGateMode: "normal",
		explicitApprovalRequired: false,
		jsonRuntimeFallbackForbidden: env !== "trusted_local",
		sandboxRequirements: [],
		explanations,
		deriverVersion: "4.0.0",
	};

	// ----- Parallelism derivation -----

	if (p === 1) {
		profile.worktreeRequired = safety === "strict" || risk === "medium" || risk === "high";
		profile.integrationQueueRequired = safety === "strict";
		profile.validationLanesRequired = true;
		profile.eventJournalRequired = safety === "strict";
		profile.admissionGateMode = safety === "strict" ? "strict" : "normal";
		explanations.push(`parallelism=${p}: minimal coordination defaults`);
	} else if (p <= 3) {
		profile.worktreeRequired = risk === "medium" || risk === "high" || safety === "strict";
		profile.integrationQueueRequired = profile.worktreeRequired;
		profile.validationLanesRequired = true;
		profile.eventJournalRequired = safety === "strict";
		profile.admissionGateMode = safety === "strict" ? "strict" : "normal";
		explanations.push(`parallelism=${p}: conditional worktree/integration requirements`);
	} else if (p <= 6) {
		profile.worktreeRequired = true;
		profile.integrationQueueRequired = true;
		profile.validationLanesRequired = true;
		profile.eventJournalRequired = true;
		profile.attemptScopedArtifactsRequired = true;
		profile.admissionGateMode = "strict";
		profile.heavyValidationMax = 1;
		profile.targetedValidationMax = 3;
		profile.jsonRuntimeFallbackForbidden = true;
		explanations.push(`parallelism=${p}: strict execution controls required`);
	} else {
		// p <= 8
		profile.worktreeRequired = true;
		profile.integrationQueueRequired = true;
		profile.validationLanesRequired = true;
		profile.eventJournalRequired = true;
		profile.attemptScopedArtifactsRequired = true;
		profile.admissionGateMode = "strict";
		profile.explicitApprovalRequired = true;
		profile.jsonRuntimeFallbackForbidden = true;
		explanations.push(`parallelism=${p}: explicit scale_8 approval and stress readiness required`);
	}

	// ----- Safety level derivation -----

	if (safety === "strict") {
		profile.eventJournalRequired = true;
		profile.integrationQueueRequired = true;
		profile.attemptScopedArtifactsRequired = true;
		profile.jsonRuntimeFallbackForbidden = true;
		explanations.push("strict safety: event journal, integration queue, scoped artifacts, JSON fallback forbidden");
	}

	// ----- Conflict risk derivation -----

	if (risk === "medium") {
		profile.worktreeRequired = p >= 2 || profile.worktreeRequired;
		profile.integrationQueueRequired = true;
		profile.writeSetDriftDetectionRequired = true;
		explanations.push("medium conflict risk: worktree isolation and drift detection");
	}
	if (risk === "high") {
		profile.worktreeRequired = true;
		profile.integrationQueueRequired = true;
		profile.writeSetDriftDetectionRequired = true;
		profile.writeSetDriftBlockOnConflict = true;
		explanations.push("high conflict risk: blocking drift policy");
	}

	// ----- Execution environment derivation -----

	if (env === "trusted_local") {
		profile.sandboxRequirements.push("warn: trusted_local not safe for untrusted code");
	} else if (env === "local_sandbox") {
		profile.sandboxRequirements.push(
			"cpu_memory_disk_quotas_required",
			"network_policy_required",
			"env_allowlist_required",
			"worktree_scoped_mount_required",
		);
	} else {
		// cloud_sandbox
		profile.sandboxRequirements.push(
			"cpu_memory_disk_quotas_required",
			"network_policy_required",
			"env_allowlist_required",
			"worktree_scoped_mount_required",
			"egress_firewall_required",
			"ephemeral_credentials_required",
			"per_attempt_container_vm_required",
		);
	}

	explanations.push(
		`execution environment ${env}: ${profile.sandboxRequirements.length > 0 ? profile.sandboxRequirements.join(", ") : "no additional sandbox requirements"}`,
	);

	return profile;
}
