/**
 * P20 Dogfood Verification Test
 *
 * Validates the overnight execution pipeline components:
 * - OvernightOrchestrator lifecycle (schedule, start, stop, pause, resume)
 * - Stop condition checking
 * - MorningReport generation and markdown rendering
 * - FullLoopValidator scenario execution
 * - TrustAssessor scoring
 * - DogfoodReport generation
 */

import { describe, it, expect } from "vitest";

// =========================================================================
// OvernightOrchestrator
// =========================================================================

describe("P20.A — OvernightOrchestrator", () => {
	it("exports OvernightOrchestrator class", async () => {
		const mod = await import("../../../src/brain/overnight/orchestrator");
		expect(mod.OvernightOrchestrator).toBeDefined();
	});

	it("can schedule a session", async () => {
		const mockQueue = {
			getQueuedPlans: async () => [],
			getPlanStatus: async () => "complete",
			startPlan: async () => {},
			stopPlan: async () => {},
			enqueuePlan: async () => {},
		};
		const mod = await import("../../../src/brain/overnight/orchestrator");
		const orchestrator = new mod.OvernightOrchestrator(mockQueue);
		const session = await orchestrator.schedule({
			planExecIds: ["plan-1", "plan-2"],
			autonomyLevel: 3,
			stopConditions: ["max_duration_reached"],
			maxDurationHours: 8,
			notificationEnabled: false,
			generateMorningReport: true,
		});
		expect(session).toBeDefined();
		expect(session.status).toBe("scheduled");
		expect(session.progress.total).toBe(2);
		expect(session.progress.completed).toBe(0);
	});

	it("can get session history", async () => {
		const mockQueue = {
			getQueuedPlans: async () => [],
			getPlanStatus: async () => "complete",
			startPlan: async () => {},
			stopPlan: async () => {},
			enqueuePlan: async () => {},
		};
		const mod = await import("../../../src/brain/overnight/orchestrator");
		const orchestrator = new mod.OvernightOrchestrator(mockQueue);
		const history = orchestrator.getHistory();
		expect(Array.isArray(history)).toBe(true);
	});

	it("can stop a running session", async () => {
		const mockQueue = {
			getQueuedPlans: async () => [],
			getPlanStatus: async () => "complete",
			startPlan: async () => {},
			stopPlan: async () => {},
			enqueuePlan: async () => {},
		};
		const mod = await import("../../../src/brain/overnight/orchestrator");

		// Create a fresh orchestrator for this test (use schedule + manual steps)
		const orchestrator = new mod.OvernightOrchestrator(mockQueue);
		await orchestrator.schedule({
			planExecIds: ["plan-1"],
			autonomyLevel: 3,
			stopConditions: [],
			maxDurationHours: 8,
			notificationEnabled: false,
			generateMorningReport: true,
		});

		// Directly stop without starting — tests stop on a scheduled session
		await orchestrator.stop("Test stop");

		const session = orchestrator.getSession();
		expect(session).not.toBeNull();
		if (session) {
			expect(session.stopReason).toBe("Test stop");
		}
	});
});

// =========================================================================
// MorningReportGenerator
// =========================================================================

describe("P20.B — MorningReportGenerator", () => {
	it("exports MorningReportGenerator class", async () => {
		const mod = await import("../../../src/brain/overnight/morning-report");
		expect(mod.MorningReportGenerator).toBeDefined();
	});

	it("generates a report from a session", async () => {
		const mod = await import("../../../src/brain/overnight/morning-report");
		const generator = new mod.MorningReportGenerator();
		const session = {
			id: "test-session",
			planExecIds: ["plan-1"],
			status: "completed" as const,
			startedAt: new Date().toISOString(),
			completedAt: new Date().toISOString(),
			progress: { completed: 1, total: 1, failed: 0 },
			createdAt: new Date().toISOString(),
		};
		const report = await generator.generate(session);
		expect(report.title).toContain("1/1");
		expect(report.plansCompleted).toBe(1);
		expect(report.plansFailed).toBe(0);
		expect(report.generatedBy).toBe("MorningReportGenerator");
	});

	it("renders markdown correctly", async () => {
		const mod = await import("../../../src/brain/overnight/morning-report");
		const generator = new mod.MorningReportGenerator();
		const session = {
			id: "test-session",
			planExecIds: [],
			status: "completed" as const,
			startedAt: new Date().toISOString(),
			completedAt: new Date().toISOString(),
			progress: { completed: 2, total: 3, failed: 1 },
			createdAt: new Date().toISOString(),
		};
		const report = await generator.generate(session);
		const md = await generator.renderMarkdown(report);
		expect(md).toContain("completed");
		expect(md).toContain("Generated by");
	});
});

// =========================================================================
// FullLoopValidator
// =========================================================================

describe("P20.C — FullLoopValidator", () => {
	it("exports FullLoopValidator class", async () => {
		const mod = await import("../../../src/brain/overnight/validation");
		expect(mod.FullLoopValidator).toBeDefined();
	});

	it("has 5 built-in scenarios", async () => {
		const mod = await import("../../../src/brain/overnight/validation");
		const validator = new mod.FullLoopValidator();
		const scenarios = validator.listScenarios();
		expect(scenarios.length).toBe(5);
	});

	it("can run a scenario by ID", async () => {
		const mod = await import("../../../src/brain/overnight/validation");
		const validator = new mod.FullLoopValidator();
		const result = await validator.runScenarioById("full_autonomous");
		expect(result).not.toBeNull();
		if (result) {
			expect(result.scenarioId).toBe("full_autonomous");
		}
	});

	it("can run all scenarios", async () => {
		const mod = await import("../../../src/brain/overnight/validation");
		const validator = new mod.FullLoopValidator();
		const results = await validator.runAllScenarios();
		expect(results.size).toBe(5);
	});

	it("registers scenarios accessible via getScenario", async () => {
		const mod = await import("../../../src/brain/overnight/validation");
		const validator = new mod.FullLoopValidator();
		const scenario = validator.getScenario("safety_stop");
		expect(scenario).toBeDefined();
		expect(scenario!.id).toBe("safety_stop");
	});
});

// =========================================================================
// TrustAssessor
// =========================================================================

describe("P20.D — TrustAssessor", () => {
	it("exports TrustAssessor class", async () => {
		const mod = await import("../../../src/brain/overnight/trust-assessment");
		expect(mod.TrustAssessor).toBeDefined();
	});

	it("generates a full trust assessment", async () => {
		const mod = await import("../../../src/brain/overnight/trust-assessment");
		const assessor = new mod.TrustAssessor();
		const assessment = await assessor.assess();
		expect(assessment.score).toBeGreaterThanOrEqual(0);
		expect(assessment.score).toBeLessThanOrEqual(100);
		expect(assessment.dimensions.safety).toBeDefined();
		expect(assessment.dimensions.reliability).toBeDefined();
		expect(assessment.dimensions.transparency).toBeDefined();
		expect(assessment.dimensions.userControl).toBeDefined();
	});

	it("assessDimension returns correct structure", async () => {
		const mod = await import("../../../src/brain/overnight/trust-assessment");
		const assessor = new mod.TrustAssessor();
		const safety = await assessor.assessDimension("safety");
		expect(safety.score).toBeGreaterThanOrEqual(0);
		expect(safety.criteria.length).toBeGreaterThan(0);
		expect(["green", "yellow", "red"]).toContain(safety.status);
	});
});

// =========================================================================
// DogfoodReportGenerator
// =========================================================================

describe("P20.E — DogfoodReportGenerator", () => {
	it("exports DogfoodReportGenerator class", async () => {
		const mod = await import("../../../src/brain/overnight/dogfood-report");
		expect(mod.DogfoodReportGenerator).toBeDefined();
	});

	it("generates a complete dogfood report", async () => {
		const valMod = await import("../../../src/brain/overnight/validation");
		const trustMod = await import("../../../src/brain/overnight/trust-assessment");
		const reportMod = await import("../../../src/brain/overnight/dogfood-report");

		const validator = new valMod.FullLoopValidator();
		const assessor = new trustMod.TrustAssessor();
		const generator = new reportMod.DogfoodReportGenerator();

		const scenarios = await validator.runAllScenarios();
		const assessment = await assessor.assess();
		const report = await generator.generate(scenarios, assessment);

		expect(report.status).toBeDefined();
		expect(report.scenarios.length).toBe(5);
		expect(report.trust.score).toBeGreaterThanOrEqual(0);
		expect(report.signOff).toBeDefined();
	});

	it("renders markdown report", async () => {
		const valMod = await import("../../../src/brain/overnight/validation");
		const trustMod = await import("../../../src/brain/overnight/trust-assessment");
		const reportMod = await import("../../../src/brain/overnight/dogfood-report");

		const validator = new valMod.FullLoopValidator();
		const assessor = new trustMod.TrustAssessor();
		const generator = new reportMod.DogfoodReportGenerator();

		const scenarios = await validator.runAllScenarios();
		const assessment = await assessor.assess();
		const report = await generator.generate(scenarios, assessment);
		const md = await generator.renderMarkdown(report);

		expect(md).toContain("Dogfood Report");
		expect(md).toContain("Sign-Off");
		expect(md).toContain("Trust Assessment");
	});
});

// =========================================================================
// Package exports
// =========================================================================

describe("P20 — package exports", () => {
	it("overnight index exports all classes", async () => {
		const mod = await import("../../../src/brain/overnight/index");
		expect(mod.OvernightOrchestrator).toBeDefined();
		expect(mod.MorningReportGenerator).toBeDefined();
		expect(mod.FullLoopValidator).toBeDefined();
		expect(mod.TrustAssessor).toBeDefined();
		expect(mod.DogfoodReportGenerator).toBeDefined();
	});
});
