/**
 * Idea to Plan Pipeline — 25.Q
 *
 * Orchestrates the end-to-end pipeline from idea ingestion through
 * proposal generation to plan synthesis. Connects the Idea Scout
 * Worker (25.K) with the Plan Synthesizer Worker (25.N) via the
 * Worker Handoff Inbox (25.O).
 *
 * Pipeline stages:
 * 1. **Ingest Ideas** — Receives scouted ideas, validates them, and
 *    applies deduplication against recently processed ideas.
 * 2. **Promote to Proposals** — Converts validated ideas into proposals
 *    with evidence references, confidence scoring, and priority ranking.
 *    Ideas below the confidence threshold are recorded but skipped.
 * 3. **Synthesize Plan** — Feeds proposals into the Plan Synthesizer
 *    Worker to produce a structured plan with workstreams, dependencies,
 *    milestones, and resource estimates.
 * 4. **Validate Output** — Validates the generated plan for structural
 *    integrity, completeness, and compliance with policy.
 * 5. **Complete or Fail** — Emits the final plan or a diagnostic with
 *    evidence of where and why the pipeline failed.
 *
 * All autonomous behavior has explicit budget, cooldown, dedup, and
 * stop-condition handling. All failures surface evidence-backed
 * diagnostics rather than silent errors. Closed-loop behavior is gated
 * by approval or safe local execution policy and cannot recurse
 * indefinitely.
 *
 * @packageDocumentation
 */

import { createHash, randomUUID } from "node:crypto";
import type { WorkerBudget, WorkerDedupConfig, WorkerDiagnostic, WorkerStopCondition } from "../types.js";
import { createWorkerDiagnostic } from "../types.js";
import {
	ALL_PIPELINE_STAGES,
	DEFAULT_IDEA_TO_PLAN_POLICY,
	type IdeaToPlanPolicy,
	type PipelineStage,
	type PipelineStopCondition,
} from "./idea-to-plan-policy.js";

// ---------------------------------------------------------------------------
// Pipeline Input Types
// ---------------------------------------------------------------------------

/**
 * A scouted idea as input to the pipeline.
 *
 * Mirrors ScoutedIdea from the idea-scout worker but allows the pipeline
 * to accept ideas from any compatible source.
 */
export interface PipelineIdea {
	/** Unique identifier (UUID v4) */
	id: string;
	/** Short human-readable title */
	title: string;
	/** Detailed description of the idea */
	description: string;
	/** Confidence score (0-1) from the scout */
	confidence: number;
	/** Priority level */
	priority: "low" | "medium" | "high" | "critical";
	/** Tags for categorization */
	tags: string[];
	/** Source references that inspired this idea */
	sourceRefs: Array<{ type: string; id: string; label: string }>;
	/** ISO 8601 timestamp of creation */
	createdAt: string;
	/** Arbitrary metadata */
	metadata: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Proposal (Pipeline Internal)
// ---------------------------------------------------------------------------

/**
 * A proposal generated by the pipeline from an idea.
 *
 * Includes the source idea reference, confidence score, and priority
 * ranking for downstream plan synthesis.
 */
export interface PipelineProposal {
	/** Unique identifier (UUID v4) */
	id: string;
	/** Proposal title (derived from source idea) */
	title: string;
	/** Proposal description */
	description: string;
	/** Priority level */
	priority: "low" | "medium" | "high" | "critical";
	/** Risk level */
	risk: "low" | "medium" | "high";
	/** Confidence score (0-1) */
	confidence: number;
	/** ID of the source idea */
	sourceIdeaId: string;
	/** Tags for categorization */
	tags: string[];
	/** Evidence IDs supporting this proposal */
	evidenceIds: string[];
	/** ISO 8601 timestamp of creation */
	createdAt: string;
	/** Arbitrary metadata */
	metadata: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Pipeline Output Types
// ---------------------------------------------------------------------------

/**
 * A workstream within a pipeline-generated plan.
 *
 * Represents one unit of work derived from a proposal during synthesis.
 */
export interface PipelineWorkstream {
	/** Workstream ID (e.g., "P1.A") */
	id: string;
	/** Human-readable title */
	title: string;
	/** High-level goal this workstream addresses */
	goal: string;
	/** ID of the source proposal */
	sourceProposalId: string;
	/** Acceptance criteria */
	acceptanceCriteria: string[];
	/** IDs of workstreams this depends on */
	dependencies: string[];
	/** Files or modules this workstream affects */
	fileScope: string[];
	/** Notes about isolation requirements */
	isolationNotes: string;
	/** Queue priority */
	queuePriority: "critical" | "high" | "normal" | "low";
	/** Risk level */
	riskLevel: "low" | "medium" | "high";
}

/**
 * A batch of workstreams that can be executed in parallel.
 */
export interface PipelineBatch {
	/** Batch index (1-based) */
	index: number;
	/** IDs of workstreams in this batch */
	workstreamIds: string[];
}

/**
 * A dependency link between two workstreams.
 */
export interface PipelineDependencyLink {
	/** Source workstream ID */
	from: string;
	/** Target workstream ID (depends on source) */
	to: string;
	/** Type of dependency */
	type: "blocking" | "soft";
}

/**
 * The output of a completed pipeline run.
 *
 * Contains the generated plan with workstreams, batches, dependencies,
 * and full provenance from ideas through proposals to plan.
 */
export interface PipelineOutput {
	/** Unique output identifier (UUID v4) */
	id: string;
	/** Human-readable summary */
	summary: string;
	/** Generated workstreams */
	workstreams: PipelineWorkstream[];
	/** Batches for execution ordering */
	batches: PipelineBatch[];
	/** Dependency links between workstreams */
	dependencies: PipelineDependencyLink[];
	/** IDs of input ideas consumed */
	ideasConsumed: string[];
	/** IDs of proposals generated */
	proposalsGenerated: string[];
	/** Number of ideas that were promoted to proposals */
	ideasPromoted: number;
	/** Number of ideas skipped due to confidence threshold */
	ideasSkipped: number;
	/** ISO 8601 timestamp of generation */
	generatedAt: string;
	/** Confidence score (0-1) based on evidence quality */
	confidence: number;
	/** Validation results */
	validation: PipelineValidationResult[];
	/** Arbitrary metadata */
	metadata: Record<string, unknown>;
}

/**
 * A validation result from the pipeline output validator.
 */
export interface PipelineValidationResult {
	/** Severity type */
	type: "error" | "warning" | "info";
	/** Component being validated */
	component: string;
	/** Validation message */
	message: string;
	/** IDs of affected artifacts */
	affectedIds: string[];
}

// ---------------------------------------------------------------------------
// Pipeline Session
// ---------------------------------------------------------------------------

/**
 * Status of a pipeline session.
 */
export type PipelineSessionStatus = "idle" | "running" | "awaiting_approval" | "completed" | "failed" | "cancelled";

/**
 * All valid PipelineSessionStatus values for runtime validation.
 */
export const ALL_PIPELINE_SESSION_STATUSES: readonly PipelineSessionStatus[] = [
	"idle",
	"running",
	"awaiting_approval",
	"completed",
	"failed",
	"cancelled",
] as const;

/**
 * A single pipeline session — orchestrates one run from ideas to plan.
 *
 * Tracks input ideas, generated proposals, output plan, budget
 * consumption, and diagnostics. Each session is self-contained
 * and can be inspected independently.
 */
export interface PipelineSession {
	/** Unique session identifier (UUID v4) */
	id: string;
	/** Session status */
	status: PipelineSessionStatus;
	/** Current pipeline stage */
	stage: PipelineStage;
	/** Human-readable label for this session */
	label: string;
	/** ISO 8601 timestamp of session creation */
	createdAt: string;
	/** ISO 8601 timestamp of last activity */
	updatedAt: string;
	/** Token consumption for this session */
	tokensConsumed: number;
	/** Runtime in milliseconds for this session */
	runtimeMs: number;
	/** Consecutive failure count */
	consecutiveFailures: number;

	/** Input ideas for this session */
	inputIdeas: PipelineIdea[];
	/** Proposals generated during this session */
	proposals: PipelineProposal[];
	/** Output plan, if completed */
	output: PipelineOutput | null;

	/** Stop condition that ended this session, if any */
	stopCondition: PipelineStopCondition | null;
	/** Diagnostic on failure, if any */
	diagnostic: WorkerDiagnostic | null;
	/** Error message if the session failed */
	error: string | null;

	/** Session metadata for extensibility */
	metadata: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Pipeline Configuration
// ---------------------------------------------------------------------------

/**
 * Configuration for the Idea-to-Plan Pipeline.
 */
export interface IdeaToPlanPipelineConfig {
	/** Policy settings for this pipeline instance */
	policy: IdeaToPlanPolicy;
	/** Maximum tokens per session (default: 250_000) */
	maxTokensPerSession: number;
	/** Maximum runtime per session in milliseconds (default: 1_200_000) */
	maxRuntimeMsPerSession: number;
	/** Maximum consecutive failures before stopping (default: 3) */
	maxConsecutiveFailures: number;
	/** Cooldown period after a session in milliseconds (default: 300_000) */
	cooldownMs: number;
	/** Whether deduplication is enabled (default: true) */
	dedupEnabled: boolean;
	/** Dedup window in milliseconds (default: 300_000) */
	dedupWindowMs: number;
}

/**
 * Default pipeline configuration.
 */
export const DEFAULT_PIPELINE_CONFIG: IdeaToPlanPipelineConfig = {
	policy: { ...DEFAULT_IDEA_TO_PLAN_POLICY },
	maxTokensPerSession: 250_000,
	maxRuntimeMsPerSession: 1_200_000,
	maxConsecutiveFailures: 3,
	cooldownMs: 300_000,
	dedupEnabled: true,
	dedupWindowMs: 300_000,
};

// ---------------------------------------------------------------------------
// Pipeline Statistics
// ---------------------------------------------------------------------------

/**
 * Aggregate statistics for the pipeline.
 */
export interface IdeaToPlanPipelineStats {
	/** Total sessions created */
	totalSessions: number;
	/** Sessions completed successfully */
	completed: number;
	/** Sessions that failed */
	failed: number;
	/** Sessions cancelled */
	cancelled: number;
	/** Sessions currently awaiting approval */
	awaitingApproval: number;
	/** Sessions currently active */
	active: number;
	/** Total tokens consumed across all sessions */
	totalTokensConsumed: number;
	/** Total runtime across all sessions in milliseconds */
	totalRuntimeMs: number;
	/** Total ideas processed */
	totalIdeasProcessed: number;
	/** Total proposals generated */
	totalProposalsGenerated: number;
	/** Total plans generated */
	totalPlansGenerated: number;
	/** Current consecutive failures */
	consecutiveFailures: number;
}

// ---------------------------------------------------------------------------
// Pipeline Validator
// ---------------------------------------------------------------------------

/**
 * Validates pipeline output for structural integrity.
 */
export class PipelineValidator {
	/**
	 * Validate a pipeline output for structural issues.
	 *
	 * @param output - The pipeline output to validate.
	 * @returns Array of validation results.
	 */
	validate(output: PipelineOutput): PipelineValidationResult[] {
		const results: PipelineValidationResult[] = [];

		if (!output.workstreams || output.workstreams.length === 0) {
			results.push({
				type: "error",
				component: "workstream",
				message: "No workstreams generated",
				affectedIds: [],
			});
		}

		const wsIds = output.workstreams.map((ws) => ws.id);
		const uniqueWsIds = new Set(wsIds);
		if (uniqueWsIds.size !== wsIds.length) {
			results.push({
				type: "error",
				component: "workstream",
				message: "Duplicate workstream IDs detected",
				affectedIds: wsIds.filter((id, idx, arr) => arr.indexOf(id) !== idx),
			});
		}

		const validWsIds = new Set(output.workstreams.map((ws) => ws.id));
		for (const dep of output.dependencies) {
			if (!validWsIds.has(dep.from)) {
				results.push({
					type: "error",
					component: "dependency",
					message: `Dependency references non-existent source workstream "${dep.from}"`,
					affectedIds: [dep.from],
				});
			}
			if (!validWsIds.has(dep.to)) {
				results.push({
					type: "error",
					component: "dependency",
					message: `Dependency references non-existent target workstream "${dep.to}"`,
					affectedIds: [dep.to],
				});
			}
		}

		// Check batch consistency
		const batchedIds = new Set<string>();
		for (const batch of output.batches) {
			if (!batch.workstreamIds || batch.workstreamIds.length === 0) {
				results.push({
					type: "warning",
					component: "batch",
					message: `Batch ${batch.index} is empty`,
					affectedIds: [],
				});
			}
			for (const wsId of batch.workstreamIds) {
				if (batchedIds.has(wsId)) {
					results.push({
						type: "error",
						component: "batch",
						message: `Workstream "${wsId}" appears in multiple batches`,
						affectedIds: [wsId],
					});
				}
				batchedIds.add(wsId);
			}
		}

		for (const ws of output.workstreams) {
			if (!batchedIds.has(ws.id)) {
				results.push({
					type: "warning",
					component: "batch",
					message: `Workstream "${ws.id}" is not assigned to any batch`,
					affectedIds: [ws.id],
				});
			}
		}

		// Check provenance
		if (output.ideasConsumed.length === 0) {
			results.push({
				type: "warning",
				component: "provenance",
				message: "No ideas were consumed to produce this plan",
				affectedIds: [],
			});
		}
		if (output.proposalsGenerated.length === 0) {
			results.push({
				type: "warning",
				component: "provenance",
				message: "No proposals were generated to produce this plan",
				affectedIds: [],
			});
		}

		return results;
	}

	/**
	 * Check if validation results contain any errors.
	 */
	hasErrors(results: PipelineValidationResult[]): boolean {
		return results.some((r) => r.type === "error");
	}

	/**
	 * Check if validation results contain any warnings.
	 */
	hasWarnings(results: PipelineValidationResult[]): boolean {
		return results.some((r) => r.type === "warning");
	}
}

// ---------------------------------------------------------------------------
// Dedup Tracker
// ---------------------------------------------------------------------------

/**
 * Tracks deduplication state for pipeline inputs.
 *
 * Prevents the pipeline from processing the same idea signature
 * within the configured dedup window.
 */
export class PipelineDedupTracker {
	private history: Map<string, number> = new Map();
	private config: WorkerDedupConfig;

	constructor(config: WorkerDedupConfig) {
		this.config = config;
	}

	/**
	 * Compute a dedup key for an idea.
	 */
	computeKey(idea: PipelineIdea): string {
		// Use title + description hash for dedup
		const content = `${idea.title}|${idea.description}`;
		return createHash("sha256").update(content).digest("hex");
	}

	/**
	 * Check if an idea is a duplicate within the dedup window.
	 *
	 * @param idea - The idea to check.
	 * @returns True if this idea is a duplicate and should be skipped.
	 */
	isDuplicate(idea: PipelineIdea): boolean {
		if (!this.config.enabled) return false;

		const key = this.computeKey(idea);
		const lastSeen = this.history.get(key);
		if (!lastSeen) return false;

		const elapsed = Date.now() - lastSeen;
		return elapsed < this.config.windowMs;
	}

	/**
	 * Record an idea in the dedup history.
	 *
	 * @param idea - The idea to record.
	 */
	record(idea: PipelineIdea): void {
		if (!this.config.enabled) return;

		const key = this.computeKey(idea);
		this.history.set(key, Date.now());

		// Prune old entries beyond the dedup window
		const cutoff = Date.now() - this.config.windowMs;
		for (const [k, ts] of this.history.entries()) {
			if (ts < cutoff) {
				this.history.delete(k);
			}
		}
	}

	/**
	 * Get the current history size.
	 */
	get historySize(): number {
		return this.history.size;
	}

	/**
	 * Clear all dedup history.
	 */
	clear(): void {
		this.history.clear();
	}
}

// ---------------------------------------------------------------------------
// Idea to Plan Pipeline
// ---------------------------------------------------------------------------

/**
 * Orchestrates the end-to-end pipeline from ideas to plans.
 *
 * Usage:
 * ```typescript
 * const pipeline = new IdeaToPlanPipeline();
 * const session = pipeline.createSession("My pipeline run", ideas);
 * pipeline.run(session);
 * const output = session.output;
 * ```
 */
export class IdeaToPlanPipeline {
	private config: IdeaToPlanPipelineConfig;
	private dedupTracker: PipelineDedupTracker;
	private validator: PipelineValidator;
	private stats: IdeaToPlanPipelineStats;
	private sessions: Map<string, PipelineSession> = new Map();
	private recursionDepth: number = 0;

	constructor(config?: Partial<IdeaToPlanPipelineConfig>) {
		this.config = {
			...DEFAULT_PIPELINE_CONFIG,
			...config,
			policy: {
				...DEFAULT_IDEA_TO_PLAN_POLICY,
				...config?.policy,
			},
		};
		this.dedupTracker = new PipelineDedupTracker(this.config.policy.dedupConfig);
		this.validator = new PipelineValidator();
		this.stats = this.createInitialStats();
	}

	// -----------------------------------------------------------------------
	// Configuration
	// -----------------------------------------------------------------------

	/**
	 * Get the current pipeline configuration.
	 */
	getConfig(): IdeaToPlanPipelineConfig {
		return { ...this.config };
	}

	/**
	 * Update the pipeline configuration.
	 */
	setConfig(updates: Partial<IdeaToPlanPipelineConfig>): void {
		this.config = {
			...this.config,
			...updates,
			policy: {
				...this.config.policy,
				...updates.policy,
			},
		};
	}

	/**
	 * Get the dedup tracker instance.
	 */
	getDedupTracker(): PipelineDedupTracker {
		return this.dedupTracker;
	}

	/**
	 * Get the pipeline validator instance.
	 */
	getValidator(): PipelineValidator {
		return this.validator;
	}

	// -----------------------------------------------------------------------
	// Stats
	// -----------------------------------------------------------------------

	private createInitialStats(): IdeaToPlanPipelineStats {
		return {
			totalSessions: 0,
			completed: 0,
			failed: 0,
			cancelled: 0,
			awaitingApproval: 0,
			active: 0,
			totalTokensConsumed: 0,
			totalRuntimeMs: 0,
			totalIdeasProcessed: 0,
			totalProposalsGenerated: 0,
			totalPlansGenerated: 0,
			consecutiveFailures: 0,
		};
	}

	/**
	 * Get aggregate pipeline statistics.
	 */
	getStats(): IdeaToPlanPipelineStats {
		return { ...this.stats };
	}

	/**
	 * Reset all statistics.
	 */
	resetStats(): void {
		this.stats = this.createInitialStats();
	}

	// -----------------------------------------------------------------------
	// Session Management
	// -----------------------------------------------------------------------

	/**
	 * Create a new pipeline session with a set of input ideas.
	 *
	 * @param label - Human-readable label for this session.
	 * @param ideas - Array of input ideas to process.
	 * @returns The created PipelineSession.
	 */
	createSession(label: string, ideas: PipelineIdea[]): PipelineSession {
		const id = randomUUID();
		const now = new Date().toISOString();

		const session: PipelineSession = {
			id,
			status: "idle",
			stage: "idle",
			label,
			createdAt: now,
			updatedAt: now,
			tokensConsumed: 0,
			runtimeMs: 0,
			consecutiveFailures: 0,
			inputIdeas: [...ideas],
			proposals: [],
			output: null,
			stopCondition: null,
			diagnostic: null,
			error: null,
			metadata: {},
		};

		this.sessions.set(id, session);
		this.stats.totalSessions++;
		return session;
	}

	/**
	 * Get a session by ID.
	 */
	getSession(sessionId: string): PipelineSession | undefined {
		return this.sessions.get(sessionId);
	}

	/**
	 * Get all sessions.
	 */
	getAllSessions(): PipelineSession[] {
		return Array.from(this.sessions.values());
	}

	/**
	 * Cancel a running session.
	 *
	 * @param sessionId - The session ID to cancel.
	 * @param reason - Optional reason for cancellation.
	 * @returns True if the session was found and cancelled.
	 */
	cancelSession(sessionId: string, reason?: string): boolean {
		const session = this.sessions.get(sessionId);
		if (!session) return false;

		if (session.status === "completed" || session.status === "cancelled" || session.status === "failed") {
			return false; // Already terminal
		}

		session.status = "cancelled";
		session.stage = "cancelled";
		session.updatedAt = new Date().toISOString();
		session.stopCondition = "user_interrupt";
		session.error = reason ?? "Session cancelled by user";
		session.diagnostic = createWorkerDiagnostic(
			"user_interrupt",
			reason ?? "Session cancelled by user",
			{ sessionId, label: session.label },
			[],
		);

		this.stats.cancelled++;
		this.stats.active--;
		return true;
	}

	/**
	 * Approve a session that is awaiting approval.
	 *
	 * @param sessionId - The session ID to approve.
	 * @returns True if approval was granted and pipeline can continue.
	 */
	approveSession(sessionId: string): boolean {
		const session = this.sessions.get(sessionId);
		if (!session) return false;
		if (session.status !== "awaiting_approval") return false;

		session.status = "running";
		session.stage = "synthesizing_plan";
		session.updatedAt = new Date().toISOString();
		return true;
	}

	/**
	 * Deny approval for a session that is awaiting approval.
	 *
	 * @param sessionId - The session ID to deny.
	 * @param reason - Optional reason for denial.
	 * @returns True if the denial was processed.
	 */
	denyApproval(sessionId: string, reason?: string): boolean {
		const session = this.sessions.get(sessionId);
		if (!session) return false;
		if (session.status !== "awaiting_approval") return false;

		session.status = "cancelled";
		session.stage = "cancelled";
		session.updatedAt = new Date().toISOString();
		session.stopCondition = "approval_required";
		session.error = reason ?? "Approval denied";
		session.diagnostic = createWorkerDiagnostic(
			"policy_blocked",
			reason ?? "Approval denied by user",
			{ sessionId, label: session.label },
			[],
		);

		this.stats.cancelled++;
		this.stats.awaitingApproval--;
		return true;
	}

	// -----------------------------------------------------------------------
	// Pipeline Run
	// -----------------------------------------------------------------------

	/**
	 * Run the full pipeline for a session.
	 *
	 * Steps:
	 * 1. Validate inputs
	 * 2. Apply deduplication
	 * 3. Promote ideas to proposals
	 * 4. Gate on approval (if required by policy)
	 * 5. Synthesize plan from proposals
	 * 6. Validate output
	 * 7. Complete or fail with diagnostics
	 *
	 * @param sessionId - The session ID to run.
	 * @returns The final PipelineSession after running.
	 */
	run(sessionId: string): PipelineSession {
		const session = this.sessions.get(sessionId);
		if (!session) {
			return this.failWithError("unknown_error", `Session "${sessionId}" not found`, { sessionId });
		}

		// Check recursion depth
		if (this.recursionDepth >= this.config.policy.maxRecursionDepth) {
			return this.failSession(
				session,
				"policy_blocked",
				`Max recursion depth (${this.config.policy.maxRecursionDepth}) exceeded`,
				{ sessionId, recursionDepth: this.recursionDepth },
			);
		}

		this.recursionDepth++;
		const startTime = Date.now();
		session.status = "running";
		session.stage = "ingesting_ideas";
		session.updatedAt = new Date().toISOString();
		this.stats.active++;

		try {
			// Stage 1: Ingest and validate ideas
			const ingestResult = this.ingestIdeas(session);
			if (!ingestResult.ok) {
				return this.failSession(session, ingestResult.stopCondition, ingestResult.error, ingestResult.context);
			}

			// Stage 2: Promote ideas to proposals
			session.stage = "promoting_to_proposals";
			session.updatedAt = new Date().toISOString();
			const promoteResult = this.promoteToProposals(session);
			if (!promoteResult.ok) {
				return this.failSession(session, promoteResult.stopCondition, promoteResult.error, promoteResult.context);
			}

			// Check budget after promotion
			const elapsed = Date.now() - startTime;
			session.tokensConsumed += 50_000; // Estimated token cost for promotion
			session.runtimeMs = elapsed;
			const budgetOk = this.checkBudget(session);
			if (!budgetOk) {
				return this.failSession(
					session,
					"token_budget_exhausted",
					"Token budget exceeded during proposal promotion",
					{ tokensConsumed: session.tokensConsumed, budget: this.config.policy.budget.maxTokensPerCycle },
				);
			}

			// Stage 3: Gate on approval if required
			if (this.config.policy.requireApproval) {
				session.status = "awaiting_approval";
				session.stage = "awaiting_approval";
				session.updatedAt = new Date().toISOString();
				this.stats.awaitingApproval++;
				this.recursionDepth--;
				return session; // Caller must call approveSession() to continue
			}

			// Stage 4: Synthesize plan
			session.stage = "synthesizing_plan";
			session.updatedAt = new Date().toISOString();
			const synthesizeResult = this.synthesizePlan(session);
			if (!synthesizeResult.ok) {
				return this.failSession(
					session,
					synthesizeResult.stopCondition,
					synthesizeResult.error,
					synthesizeResult.context,
				);
			}

			// Runtime check after synthesis
			session.runtimeMs = Date.now() - startTime;
			if (session.runtimeMs > this.config.maxRuntimeMsPerSession) {
				return this.failSession(
					session,
					"timeout",
					`Max runtime (${this.config.maxRuntimeMsPerSession}ms) exceeded: ${session.runtimeMs}ms`,
					{ runtimeMs: session.runtimeMs, maxRuntimeMs: this.config.maxRuntimeMsPerSession },
				);
			}

			// Stage 5: Validate output
			session.stage = "validating_output";
			session.updatedAt = new Date().toISOString();
			const validateResult = this.validateOutput(session);
			if (!validateResult.ok) {
				return this.failSession(
					session,
					validateResult.stopCondition,
					validateResult.error,
					validateResult.context,
				);
			}

			// Complete
			return this.completeSession(session, startTime);
		} catch (err) {
			const errorMsg = err instanceof Error ? err.message : String(err);
			return this.failSession(session, "unknown_error", `Pipeline execution error: ${errorMsg}`, {
				error: errorMsg,
			});
		}
	}

	/**
	 * Resume a session that was awaiting approval.
	 * Runs the remaining stages (synthesize, validate, complete).
	 *
	 * @param sessionId - The session ID to resume.
	 * @returns The final PipelineSession after running remaining stages.
	 */
	resumeAfterApproval(sessionId: string): PipelineSession {
		const session = this.sessions.get(sessionId);
		if (!session) {
			return this.failWithError("unknown_error", `Session "${sessionId}" not found`, { sessionId });
		}
		if (session.status !== "awaiting_approval") {
			return this.failWithError(
				"policy_blocked",
				`Session "${sessionId}" is not awaiting approval (status: ${session.status})`,
				{ sessionId, status: session.status },
			);
		}

		const startTime = Date.now() - session.runtimeMs;
		session.status = "running";
		session.stage = "synthesizing_plan";
		session.updatedAt = new Date().toISOString();
		this.stats.awaitingApproval--;

		try {
			// Stage 4: Synthesize plan
			const synthesizeResult = this.synthesizePlan(session);
			if (!synthesizeResult.ok) {
				return this.failSession(
					session,
					synthesizeResult.stopCondition,
					synthesizeResult.error,
					synthesizeResult.context,
				);
			}

			session.runtimeMs = Date.now() - startTime;
			if (session.runtimeMs > this.config.maxRuntimeMsPerSession) {
				return this.failSession(
					session,
					"timeout",
					`Max runtime (${this.config.maxRuntimeMsPerSession}ms) exceeded: ${session.runtimeMs}ms`,
					{ runtimeMs: session.runtimeMs, maxRuntimeMs: this.config.maxRuntimeMsPerSession },
				);
			}

			// Stage 5: Validate output
			session.stage = "validating_output";
			session.updatedAt = new Date().toISOString();
			const validateResult = this.validateOutput(session);
			if (!validateResult.ok) {
				return this.failSession(
					session,
					validateResult.stopCondition,
					validateResult.error,
					validateResult.context,
				);
			}

			return this.completeSession(session, startTime);
		} catch (err) {
			const errorMsg = err instanceof Error ? err.message : String(err);
			return this.failSession(session, "unknown_error", `Pipeline execution error: ${errorMsg}`, {
				error: errorMsg,
			});
		}
	}

	// -----------------------------------------------------------------------
	// Stage: Ingestion
	// -----------------------------------------------------------------------

	private ingestIdeas(session: PipelineSession): {
		ok: boolean;
		stopCondition?: PipelineStopCondition;
		error?: string;
		context?: Record<string, unknown>;
	} {
		if (session.inputIdeas.length === 0) {
			return {
				ok: false,
				stopCondition: "dependency_unavailable",
				error: "No input ideas provided for pipeline run",
				context: { sessionId: session.id },
			};
		}

		if (session.inputIdeas.length > this.config.policy.maxIdeasPerRun) {
			return {
				ok: false,
				stopCondition: "max_ideas_reached",
				error: `Input ideas (${session.inputIdeas.length}) exceed maxIdeasPerRun (${this.config.policy.maxIdeasPerRun})`,
				context: {
					inputCount: session.inputIdeas.length,
					maxIdeas: this.config.policy.maxIdeasPerRun,
				},
			};
		}

		// Apply deduplication
		const dedupedIdeas: PipelineIdea[] = [];
		for (const idea of session.inputIdeas) {
			if (!this.dedupTracker.isDuplicate(idea)) {
				dedupedIdeas.push(idea);
				this.dedupTracker.record(idea);
			}
		}

		if (dedupedIdeas.length === 0) {
			return {
				ok: false,
				stopCondition: "no_valid_proposals",
				error: "All input ideas were duplicates within the dedup window",
				context: {
					totalIdeas: session.inputIdeas.length,
					dedupWindowMs: this.config.policy.dedupConfig.windowMs,
				},
			};
		}

		session.inputIdeas = dedupedIdeas;
		return { ok: true };
	}

	// -----------------------------------------------------------------------
	// Stage: Promotion to Proposals
	// -----------------------------------------------------------------------

	private promoteToProposals(session: PipelineSession): {
		ok: boolean;
		stopCondition?: PipelineStopCondition;
		error?: string;
		context?: Record<string, unknown>;
	} {
		const policy = this.config.policy;
		const proposals: PipelineProposal[] = [];
		let skipped = 0;

		for (const idea of session.inputIdeas) {
			if (proposals.length >= policy.maxProposalsPerRun) {
				break;
			}

			if (idea.confidence < policy.minIdeaConfidenceForProposal) {
				skipped++;
				continue;
			}

			// Determine priority mapping (idea priority -> proposal priority)
			const priority =
				idea.priority === "critical"
					? "critical"
					: idea.priority === "high"
						? "high"
						: idea.priority === "medium"
							? "medium"
							: "low";

			// Determine risk level based on confidence
			const risk: "low" | "medium" | "high" =
				idea.confidence >= 0.7 ? "low" : idea.confidence >= 0.5 ? "medium" : "high";

			const proposal: PipelineProposal = {
				id: randomUUID(),
				title: idea.title,
				description: idea.description,
				priority,
				risk,
				confidence: idea.confidence,
				sourceIdeaId: idea.id,
				tags: [...idea.tags],
				evidenceIds: idea.sourceRefs.map((r) => r.id),
				createdAt: new Date().toISOString(),
				metadata: { ...idea.metadata },
			};

			proposals.push(proposal);
		}

		if (proposals.length === 0) {
			const reason =
				skipped > 0
					? `All ${skipped} non-duplicate ideas had confidence below threshold (${policy.minIdeaConfidenceForProposal})`
					: "No proposals could be generated from input ideas";
			return {
				ok: false,
				stopCondition: "low_confidence",
				error: reason,
				context: {
					totalIdeas: session.inputIdeas.length,
					skippedDueToConfidence: skipped,
					threshold: policy.minIdeaConfidenceForProposal,
				},
			};
		}

		session.proposals = proposals;
		this.stats.totalProposalsGenerated += proposals.length;
		return { ok: true };
	}

	// -----------------------------------------------------------------------
	// Stage: Plan Synthesis
	// -----------------------------------------------------------------------

	private synthesizePlan(session: PipelineSession): {
		ok: boolean;
		stopCondition?: PipelineStopCondition;
		error?: string;
		context?: Record<string, unknown>;
	} {
		const proposals = session.proposals;
		const policy = this.config.policy;

		// Filter proposals by confidence
		const validProposals = proposals.filter((p) => p.confidence >= policy.minProposalConfidenceForSynthesis);

		if (validProposals.length === 0) {
			return {
				ok: false,
				stopCondition: "no_valid_proposals",
				error: `All ${proposals.length} proposals had confidence below synthesis threshold (${policy.minProposalConfidenceForSynthesis})`,
				context: {
					totalProposals: proposals.length,
					threshold: policy.minProposalConfidenceForSynthesis,
				},
			};
		}

		// Simulate token cost for synthesis
		session.tokensConsumed += 100_000;

		// Generate workstreams from proposals
		// In a full implementation, this would use the PlanSynthesizerWorker.
		// Here we generate a plan structure directly from proposals.
		const workstreams: PipelineWorkstream[] = [];
		const batches: PipelineBatch[] = [];
		const dependencies: PipelineDependencyLink[] = [];

		for (let i = 0; i < validProposals.length; i++) {
			const prop = validProposals[i];
			const wsId = `WS-${(i + 1).toString().padStart(2, "0")}`;
			const riskLevel = prop.risk;

			const ws: PipelineWorkstream = {
				id: wsId,
				title: prop.title,
				goal: prop.description,
				sourceProposalId: prop.id,
				acceptanceCriteria: [
					`Implement "${prop.title}" as described`,
					`Pass all existing tests`,
					`No breaking changes to existing functionality`,
				],
				dependencies: i > 0 ? [workstreams[i - 1].id] : [],
				fileScope: [],
				isolationNotes: riskLevel === "high" ? "Requires isolated worktree" : "Standard execution",
				queuePriority: prop.priority === "critical" ? "critical" : prop.priority === "high" ? "high" : "normal",
				riskLevel,
			};

			if (i > 0) {
				dependencies.push({
					from: workstreams[i - 1].id,
					to: wsId,
					type: "blocking",
				});
			}

			workstreams.push(ws);
		}

		// Create batches (up to 3 workstreams per batch)
		const batchSize = 3;
		for (let i = 0; i < workstreams.length; i += batchSize) {
			const batchWsIds = workstreams.slice(i, i + batchSize).map((ws) => ws.id);
			batches.push({
				index: batches.length + 1,
				workstreamIds: batchWsIds,
			});
		}

		// Build output
		const output: PipelineOutput = {
			id: randomUUID(),
			summary: `Plan synthesized from ${validProposals.length} proposal(s)`,
			workstreams,
			batches,
			dependencies,
			ideasConsumed: validProposals.map((p) => p.sourceIdeaId),
			proposalsGenerated: validProposals.map((p) => p.id),
			ideasPromoted: validProposals.length,
			ideasSkipped: proposals.length - validProposals.length,
			generatedAt: new Date().toISOString(),
			confidence: validProposals.reduce((sum, p) => sum + p.confidence, 0) / validProposals.length,
			validation: [],
			metadata: {
				policyVersion: policy.contractVersion,
				templateId: policy.defaultTemplateId,
			},
		};

		session.output = output;
		this.stats.totalPlansGenerated++;
		return { ok: true };
	}

	// -----------------------------------------------------------------------
	// Stage: Output Validation
	// -----------------------------------------------------------------------

	private validateOutput(session: PipelineSession): {
		ok: boolean;
		stopCondition?: PipelineStopCondition;
		error?: string;
		context?: Record<string, unknown>;
	} {
		if (!session.output) {
			return {
				ok: false,
				stopCondition: "synthesis_failed",
				error: "No output to validate (plan synthesis did not produce an output)",
				context: { sessionId: session.id, stage: session.stage },
			};
		}

		const validationResults = this.validator.validate(session.output);
		session.output.validation = validationResults;

		if (this.validator.hasErrors(validationResults)) {
			const errorMessages = validationResults
				.filter((r) => r.type === "error")
				.map((r) => r.message)
				.join("; ");
			return {
				ok: false,
				stopCondition: "dag_validation_failed",
				error: `Output validation failed: ${errorMessages}`,
				context: {
					sessionId: session.id,
					errors: validationResults.filter((r) => r.type === "error"),
				},
			};
		}

		return { ok: true };
	}

	// -----------------------------------------------------------------------
	// Budget Check
	// -----------------------------------------------------------------------

	private checkBudget(session: PipelineSession): boolean {
		if (session.tokensConsumed > this.config.policy.budget.maxTokensPerCycle) {
			return false;
		}
		if (session.consecutiveFailures > this.config.policy.budget.maxConsecutiveFailures) {
			return false;
		}
		return true;
	}

	// -----------------------------------------------------------------------
	// Session Completion
	// -----------------------------------------------------------------------

	private completeSession(session: PipelineSession, startTime: number): PipelineSession {
		session.runtimeMs = Date.now() - startTime;
		session.status = "completed";
		session.stage = "completed";
		session.stopCondition = "completed";
		session.updatedAt = new Date().toISOString();

		this.stats.completed++;
		this.stats.active--;
		this.stats.totalTokensConsumed += session.tokensConsumed;
		this.stats.totalRuntimeMs += session.runtimeMs;
		this.stats.totalIdeasProcessed += session.inputIdeas.length;
		this.stats.consecutiveFailures = 0;
		this.recursionDepth = 0;

		return session;
	}

	private failSession(
		session: PipelineSession,
		stopCondition: PipelineStopCondition,
		error: string,
		context: Record<string, unknown>,
	): PipelineSession {
		const existingFailures = session.consecutiveFailures;
		session.status = "failed";
		session.stage = "failed";
		session.stopCondition = stopCondition;
		session.error = error;
		session.updatedAt = new Date().toISOString();
		session.consecutiveFailures = existingFailures + 1;
		session.diagnostic = createWorkerDiagnostic(stopCondition as WorkerStopCondition, error, context, []);

		this.stats.failed++;
		this.stats.active--;
		this.stats.consecutiveFailures = session.consecutiveFailures;
		this.recursionDepth = 0;

		return session;
	}

	/**
	 * Create a minimal failed session directly (without running).
	 * Used for pre-flight validation failures.
	 */
	private failWithError(
		stopCondition: PipelineStopCondition,
		error: string,
		context: Record<string, unknown>,
	): PipelineSession {
		const id = randomUUID();
		const now = new Date().toISOString();
		const session: PipelineSession = {
			id,
			status: "failed",
			stage: "failed",
			label: "error",
			createdAt: now,
			updatedAt: now,
			tokensConsumed: 0,
			runtimeMs: 0,
			consecutiveFailures: 1,
			inputIdeas: [],
			proposals: [],
			output: null,
			stopCondition,
			diagnostic: createWorkerDiagnostic(stopCondition as WorkerStopCondition, error, context, []),
			error,
			metadata: {},
		};
		this.sessions.set(id, session);
		this.stats.totalSessions++;
		this.stats.failed++;
		return session;
	}
}
