/**
 * PlanSpec v5 Alpha2 Strict Schema — Zod-based validation (GENERATED)
 *
 * DO NOT EDIT THIS FILE BY HAND.
 * It is generated from:
 *   PlanSpec_v5_alpha2_template_pack/02_planspec_v5_alpha2_schema.json
 *
 * Regenerate by running:
 *   tsx packages/coding-agent/scripts/generate-plan-template.ts
 *
 * Every object uses .strict() (where the source schema marks
 * additionalProperties: false) to reject unknown properties. Required
 * fields are enforced; optional fields use .optional().
 */

import { z } from "zod";

// =============================================================================
// Primitive $defs
// =============================================================================

export const PlanSpecV5Alpha2_Metadata = z
	.object({
		phaseId: z.string(),
		title: z.string(),
		description: z.string().optional(),
		createdAt: z.string(),
		updatedAt: z.string().optional(),
		owner: z.string().optional(),
		status: z.enum(["draft", "validated", "locked", "admitted", "running", "completed", "superseded"]),
		sourceDocument: z.string(),
		sourcePackage: z.string().optional(),
	})
	.strict();

export const PlanSpecV5Alpha2_Compatibility = z
	.object({
		runtimeContractVersion: z.string(),
		runtimeTemplateVersion: z.string(),
		legacyTemplateCompatible: z.boolean(),
		generatedFromV411: z.boolean().optional(),
		v411AdapterRequired: z.boolean(),
		notes: z.array(z.string()).optional(),
	})
	.strict();

export const PlanSpecV5Alpha2_Intent = z
	.object({
		executionClass: z.enum(["implementation", "repair", "validation", "research"]),
		safetyLevel: z.enum(["relaxed", "standard", "strict"]),
		executionMode: z.string(),
		parallelism: z.number().int(),
		targetPromotionMode: z.string().optional(),
		p45ImplementationAllowed: z.boolean().optional(),
		p50ImplementationAllowed: z.boolean().optional(),
		humanReviewRecommended: z.boolean().optional(),
		routeBusEnabledByDefault: z.boolean().optional(),
		tabModePickerEnabled: z.boolean().optional(),
		filePickerGesture: z.string().optional(),
		summary: z.string().optional(),
	})
	.strict();

export const PlanSpecV5Alpha2_Security = z
	.object({
		schemaValidationRequired: z.boolean(),
		lockRequiredForExecution: z.boolean(),
		canonicalJsonHashRequired: z.boolean(),
		signatureRequired: z.boolean(),
		signatureAlgorithm: z.string().optional(),
		hardStops: z.array(z.string()),
		forbiddenFiles: z.array(z.string()),
	})
	.strict();

export const PlanSpecV5Alpha2_Commands = z
	.object({
		policy: z.literal("risk_tiered"),
		defaultMode: z.string(),
		shellDefault: z.string(),
		exactAllowedCommands: z.array(z.record(z.string(), z.unknown())),
		commandClasses: z.array(z.record(z.string(), z.unknown())),
		runtimeCommandGrant: z.record(z.string(), z.unknown()),
		hardDeniedCommands: z.array(z.record(z.string(), z.unknown())),
		validationEvidenceRules: z
			.object({
				finalPromotionRequiresExactAllowedCommand: z.boolean(),
				discoveryCommandsMayNotSatisfyFinalValidation: z.boolean(),
				runtimeGrantCommandsCanSatisfyValidationOnlyIfGrantStatesValidationPurpose: z.boolean(),
				accpCompileCommandsCanSatisfyAccpValidationOnlyIfArtifactHashRecorded: z.boolean().optional(),
			})
			.strict(),
	})
	.strict();

export const PlanSpecV5Alpha2_Instruction = z
	.object({
		id: z.string(),
		priority: z.enum(["must", "should", "may"]).optional(),
		kind: z.string().optional(),
		text: z.string(),
		description: z.string().optional(),
		risk: z.string().optional(),
		enforcedBy: z.array(z.string()).optional(),
	})
	.strict();

export const PlanSpecV5Alpha2_BriefNote = z
	.object({
		id: z.string(),
		text: z.string(),
		description: z.string().optional(),
		risk: z.string().optional(),
		priority: z.enum(["must", "should", "may"]).optional(),
		kind: z.string().optional(),
		enforcedBy: z.array(z.string()).optional(),
	})
	.strict();

export const PlanSpecV5Alpha2_Wave = z
	.object({
		id: z.string(),
		title: z.string(),
		description: z.string(),
		workspaceIds: z.array(z.string()),
		dependencies: z.array(z.string()),
		batchSize: z.number().int(),
		gate: z
			.object({
				required: z.boolean(),
				commandRefs: z.array(z.string()),
				requiredArtifacts: z.array(z.string()),
			})
			.strict(),
	})
	.strict();

export const PlanSpecV5Alpha2_Workspace = z
	.object({
		id: z.string(),
		title: z.string(),
		waveId: z.string(),
		dependencies: z.array(z.string()),
		role: z.string(),
		allowedFiles: z.array(z.string()).min(1),
		forbiddenFiles: z.array(z.string()),
		instructions: z.array(PlanSpecV5Alpha2_Instruction),
		acceptanceCriteria: z.array(z.record(z.string(), z.unknown())),
		validation: z.record(z.string(), z.unknown()),
		reports: z.record(z.string(), z.unknown()),
		rollback: z.record(z.string(), z.unknown()),
		description: z.string().optional(),
		risk: z.record(z.string(), z.unknown()).optional(),
	})
	.strict();

// =============================================================================
// Top-level schema
// =============================================================================

export const PlanSpecV5Alpha2Schema = z
	.object({
		$schema: z.string(),
		planSpecVersion: z.literal("5.0.0-alpha2"),
		kind: z.literal("ImplementationPlan"),
		metadata: PlanSpecV5Alpha2_Metadata,
		compatibility: PlanSpecV5Alpha2_Compatibility,
		intent: PlanSpecV5Alpha2_Intent,
		authority: z
			.object({
				executionState: z.record(z.string(), z.unknown()),
				completion: z.record(z.string(), z.unknown()),
				repositoryMutation: z.record(z.string(), z.unknown()),
				reports: z.record(z.string(), z.unknown()),
				routing: z.record(z.string(), z.unknown()).optional(),
			})
			.strict(),
		enforcementRegistry: z
			.object({
				mechanisms: z.array(z.string()),
			})
			.strict(),
		security: z
			.object({
				schemaValidationRequired: z.boolean(),
				lockRequiredForExecution: z.boolean(),
				canonicalJsonHashRequired: z.boolean(),
				signatureRequired: z.boolean(),
				signatureAlgorithm: z.string().optional(),
				hardStops: z.array(z.string()),
				forbiddenFiles: z.array(z.string()),
				operatorNotes: z.array(z.string()).optional(),
			})
			.strict(),
		commands: PlanSpecV5Alpha2_Commands,
		locking: z
			.object({
				lockVersion: z.string(),
				lockFile: z.string(),
				lockRequired: z.boolean(),
				workerMustEchoPlanLockHash: z.boolean(),
				workerMustEchoWorkspaceLockHash: z.boolean(),
				hashes: z.array(z.string()),
				lifecycle: z.array(z.string()),
				mutationRules: z.record(z.string(), z.unknown()),
			})
			.strict(),
		brief: z
			.object({
				mission: PlanSpecV5Alpha2_Instruction,
				hardRequirements: z.array(PlanSpecV5Alpha2_Instruction),
				antiPatterns: z.array(PlanSpecV5Alpha2_BriefNote),
				operatorNotes: z.array(PlanSpecV5Alpha2_BriefNote),
			})
			.strict(),
		waves: z.array(PlanSpecV5Alpha2_Wave),
		workspaces: z.array(PlanSpecV5Alpha2_Workspace),
		validation: z
			.object({
				finalRequired: z.boolean(),
				watchModeForbidden: z.boolean(),
				noTestsFoundIsFailure: z.boolean(),
				commandEvidenceRequired: z.boolean(),
				forbiddenPatterns: z.array(z.string()),
				finalValidationCommandRefs: z.array(z.string()),
				discoveryCommandsMayNotSatisfyFinalValidation: z.boolean(),
				accpRequiredArtifacts: z.array(z.string()).optional(),
			})
			.strict(),
		evidence: z
			.object({
				ledgerRequired: z.boolean(),
				confidenceEnum: z.array(z.enum(["high", "medium", "low"])),
				requiredEvidenceTypes: z.array(z.string()),
				evidenceItemRequiredFields: z.array(z.string()),
				hashWhenAvailable: z.boolean(),
				accpArtifactHashRequired: z.boolean().optional(),
			})
			.strict(),
		reports: z
			.object({
				protocol: z.literal("ACCP"),
				version: z.string(),
				required: z.array(z.unknown()),
				artifactDirectory: z.string().optional(),
				stableIdsRequired: z.boolean().optional(),
				commandEvidenceRequired: z.boolean().optional(),
				rollbackPlanRequiredForMutation: z.boolean().optional(),
				sourceFormat: z.string().optional(),
				reportsAreEvidenceOnly: z.boolean().optional(),
				reportsDoNotAuthorizeExecution: z.boolean().optional(),
				routeSignalsAreAdvisory: z.boolean().optional(),
			})
			.strict(),
		p45Bridge: z
			.object({
				implementationAllowed: z.literal(false),
				allowedArtifactPaths: z.array(z.string()),
				forbiddenRuntimePaths: z.array(z.string()),
				artifactExports: z.array(
					z
						.object({
							type: z.string(),
							path: z.string(),
						})
						.strict(),
				),
			})
			.strict()
			.optional(),
		renderHints: z
			.object({
				generatedMarkdownPath: z.string().optional(),
				includeBrief: z.boolean().optional(),
				includeWaves: z.boolean().optional(),
				includeWorkspaces: z.boolean().optional(),
				includeAcceptanceCriteria: z.boolean().optional(),
				includeValidation: z.boolean().optional(),
				markPreviewNonAuthoritative: z.boolean().optional(),
			})
			.strict()
			.optional(),
		migration: z
			.object({
				from: z.string().optional(),
				strategy: z.string().optional(),
				adapterRequired: z.boolean().optional(),
				legacyFieldsMapped: z
					.array(
						z
							.object({
								v411: z.string(),
								planspec: z.string(),
							})
							.strict(),
					)
					.optional(),
			})
			.strict()
			.optional(),
		sourceReferences: z.record(z.string(), z.unknown()).optional(),
		accp: z.record(z.string(), z.unknown()).optional(),
		finalPromotion: z.record(z.string(), z.unknown()).optional(),
	})
	.strict();
