/**
 * NotificationPreferences — Settings UI for notification channel and
 * delivery preferences (24.H).
 *
 * Allows users to:
 * - Enable/disable notifications globally
 * - Toggle individual delivery channels (email, inbox, system)
 * - Configure per-type routing rules
 * - Reset to defaults
 *
 * States:
 * - Loading: Shows a spinner while preferences are fetched
 * - Empty: Shows default/empty state when no preferences exist
 * - Error: Shows error message with retry option
 * - Success: Interactive form with save feedback
 */

import {
	Bell,
	BellOff,
	Mail,
	Inbox,
	Monitor,
	RefreshCw,
	AlertTriangle,
	CheckCircle,
	RotateCcw,
} from "lucide-react";
import { useState, useEffect, useMemo, useCallback } from "react";
import {
	useNotificationPreferences,
	type NotificationChannel,
	type NotificationType,
	type ChannelRule,
} from "../../hooks/useNotificationPreferences";

// ─── Style constants (matching SettingsDialog) ────────────────────────────

const inputClass =
	"w-full px-3 py-2 text-sm bg-white dark:bg-[#1E1E1E] border border-[#E8E6E1] dark:border-[#333] rounded text-stone-800 dark:text-stone-200 placeholder:text-stone-400 focus:outline-none focus:border-blue-500";
const labelClass = "text-xs text-stone-500 dark:text-stone-400 block mb-1";
const toggleClass =
	"relative inline-flex h-5 w-9 items-center rounded-full transition-colors focus:outline-none";
const toggleActiveClass = "bg-blue-600";
const toggleInactiveClass = "bg-stone-100 dark:bg-[#2A2A2A]";

// ─── Notification type display names ──────────────────────────────────────

const NOTIFICATION_TYPE_LABELS: Record<NotificationType, string> = {
	plan_completed: "Plan Completed",
	plan_failed: "Plan Failed",
	task_completed: "Task Completed",
	task_failed: "Task Failed",
	approval_required: "Approval Required",
	proposal_generated: "Proposal Generated",
	goal_drift: "Goal Drift",
	memory_conflict: "Memory Conflict",
	daemon_alert: "Daemon Alert",
	brain_observation: "Brain Observation",
	warning: "Warning",
	info: "Info",
};

const NOTIFICATION_TYPE_DESCRIPTIONS: Record<NotificationType, string> = {
	plan_completed: "When a plan execution finishes successfully",
	plan_failed: "When a plan execution fails or errors out",
	task_completed: "When a task within a plan is completed",
	task_failed: "When a task within a plan fails",
	approval_required: "When a plan requires explicit approval",
	proposal_generated: "When a new proposal is generated by the brain",
	goal_drift: "When a goal drifts from its defined trajectory",
	memory_conflict: "When memory conflicts are detected",
	daemon_alert: "Important daemon-level alerts",
	brain_observation: "General brain observations and insights",
	warning: "Warnings from any system component",
	info: "General informational notifications",
};

// ─── Channel icon map ─────────────────────────────────────────────────────

const CHANNEL_ICONS: Record<NotificationChannel, React.ReactNode> = {
	email: <Mail size={14} strokeWidth={2} />,
	inbox: <Inbox size={14} strokeWidth={2} />,
	system: <Monitor size={14} strokeWidth={2} />,
};

const CHANNEL_LABELS: Record<NotificationChannel, string> = {
	email: "Email",
	inbox: "Pi Inbox",
	system: "System",
};

// ─── Toggle component ─────────────────────────────────────────────────────

interface ToggleProps {
	enabled: boolean;
	onToggle: () => void;
	disabled?: boolean;
}

function Toggle({ enabled, onToggle, disabled }: ToggleProps) {
	return (
		<button
			type="button"
			onClick={onToggle}
			disabled={disabled}
			className={`${toggleClass} ${enabled ? toggleActiveClass : toggleInactiveClass} ${
				disabled ? "opacity-40 cursor-not-allowed" : ""
			}`}
		>
			<span
				className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
					enabled ? "translate-x-[18px]" : "translate-x-[2px]"
				}`}
			/>
		</button>
	);
}

// ─── ChannelRow component ─────────────────────────────────────────────────

interface ChannelRowProps {
	channel: NotificationChannel;
	enabled: boolean;
	configured: boolean;
	onToggle: () => void;
}

function ChannelRow({ channel, enabled, configured, onToggle }: ChannelRowProps) {
	return (
		<div className="flex items-center gap-3 py-2">
			<span className="text-stone-500 dark:text-stone-400 shrink-0">{CHANNEL_ICONS[channel]}</span>
			<div className="flex-1 min-w-0">
				<div className="flex items-center gap-2">
					<span className="text-sm font-medium text-stone-800 dark:text-stone-200">{CHANNEL_LABELS[channel]}</span>
					{!configured && (
						<span className="inline-flex items-center px-1.5 py-0.5 rounded text-xs font-medium bg-yellow-900/30 text-yellow-400">
							not configured
						</span>
					)}
				</div>
			</div>
			<Toggle enabled={enabled} onToggle={onToggle} disabled={!configured} />
		</div>
	);
}

// ─── TypeRuleRow component ────────────────────────────────────────────────

interface TypeRuleRowProps {
	type: NotificationType;
	rules: ChannelRule;
	onRuleChange: (type: NotificationType, channel: NotificationChannel, enabled: boolean) => void;
}

function TypeRuleRow({ type, rules, onRuleChange }: TypeRuleRowProps) {
	return (
		<div className="py-2 border-b border-[#E8E6E1] dark:border-[#333]/50 last:border-b-0">
			<div className="flex items-center justify-between mb-1">
				<span className="text-sm font-medium text-stone-800 dark:text-stone-200">{NOTIFICATION_TYPE_LABELS[type]}</span>
			</div>
			<p className="text-xs text-stone-400 dark:text-stone-500 mb-1.5">{NOTIFICATION_TYPE_DESCRIPTIONS[type]}</p>
			<div className="flex items-center gap-4">
				{(Object.keys(CHANNEL_LABELS) as NotificationChannel[]).map((ch) => (
					<label key={ch} className="flex items-center gap-1.5 text-xs text-stone-500 dark:text-stone-400 cursor-pointer">
						<input
							type="checkbox"
							checked={rules[ch] ?? true}
							onChange={() => onRuleChange(type, ch, !(rules[ch] ?? true))}
							className="rounded border-[#E8E6E1] dark:border-[#333] text-blue-500 focus:ring-blue-500 focus:ring-offset-0 bg-stone-100 dark:bg-[#2A2A2A]"
						/>
						{CHANNEL_LABELS[ch]}
					</label>
				))}
			</div>
		</div>
	);
}

// ─── Main component ───────────────────────────────────────────────────────

interface NotificationPreferencesProps {
	/** Optional class name for the wrapper. */
	className?: string;
}

export function NotificationPreferences({ className }: NotificationPreferencesProps) {
	const {
		preferences,
		channels,
		isLoading,
		isSaving,
		error,
		updatePreferences,
		resetPreferences,
		refetch,
	} = useNotificationPreferences();

	// ── Local form state ─────────────────────────────────────────────

	const [enabled, setEnabled] = useState(true);
	const [channelStates, setChannelStates] = useState<Record<NotificationChannel, boolean>>({
		email: false,
		inbox: true,
		system: true,
	});
	const [typeRules, setTypeRules] = useState<Partial<Record<NotificationType, ChannelRule>>>({});
	const [saved, setSaved] = useState(false);

	// Sync from preferences when they load
	useEffect(() => {
		if (preferences) {
			setEnabled(preferences.enabled);
			setChannelStates({ ...preferences.channels });
			setTypeRules({ ...preferences.rules });
		}
	}, [preferences]);

	// ── Dirty state ──────────────────────────────────────────────────

	const isDirty = useMemo(() => {
		if (!preferences) return false;
		if (enabled !== preferences.enabled) return true;
		for (const ch of Object.keys(channelStates) as NotificationChannel[]) {
			if (channelStates[ch] !== preferences.channels[ch]) return true;
		}
		// Check rules
		const allTypes = Object.keys(NOTIFICATION_TYPE_LABELS) as NotificationType[];
		for (const t of allTypes) {
			const current = typeRules[t] ?? {};
			const original = preferences.rules[t] ?? {};
			for (const ch of Object.keys(CHANNEL_LABELS) as NotificationChannel[]) {
				if ((current[ch] ?? true) !== (original[ch] ?? true)) return true;
			}
		}
		return false;
	}, [preferences, enabled, channelStates, typeRules]);

	// ── Handlers ─────────────────────────────────────────────────────

	const handleChannelToggle = useCallback(
		(channel: NotificationChannel) => {
			setChannelStates((prev) => ({ ...prev, [channel]: !prev[channel] }));
		},
		[],
	);

	const handleRuleChange = useCallback(
		(type: NotificationType, channel: NotificationChannel, value: boolean) => {
			setTypeRules((prev) => {
				const existing = prev[type] ?? {};
				return {
					...prev,
					[type]: { ...existing, [channel]: value },
				};
			});
		},
		[],
	);

	const handleSave = async () => {
		try {
			await updatePreferences({
				enabled,
				channels: channelStates,
				rules: typeRules,
			});
			setSaved(true);
			setTimeout(() => setSaved(false), 2000);
		} catch {
			// Error is surfaced via the mutation state
		}
	};

	const handleReset = async () => {
		try {
			await resetPreferences();
			setSaved(true);
			setTimeout(() => setSaved(false), 2000);
		} catch {
			// Error is surfaced via the mutation state
		}
	};

	// ── Render ───────────────────────────────────────────────────────

	// Loading state
	if (isLoading && !preferences) {
		return (
			<div className={`space-y-4 ${className ?? ""}`}>
				<p className="text-xs text-stone-400 dark:text-stone-500 mb-3">
					Configure how and when you receive notifications from Pi.
				</p>
				<div className="flex items-center justify-center py-12">
					<RefreshCw size={20} className="text-stone-400 dark:text-stone-500 animate-spin" />
					<span className="ml-2 text-sm text-stone-400 dark:text-stone-500">Loading notification preferences...</span>
				</div>
			</div>
		);
	}

	// Error state
	if (error && !preferences) {
		return (
			<div className={`space-y-4 ${className ?? ""}`}>
				<p className="text-xs text-stone-400 dark:text-stone-500 mb-3">
					Configure how and when you receive notifications from Pi.
				</p>
				<div className="flex items-center gap-3 p-4 rounded border border-red-700 bg-red-900/10">
					<AlertTriangle size={18} className="text-red-400 shrink-0" />
					<div className="flex-1 min-w-0">
						<p className="text-sm text-red-300">Failed to load notification preferences</p>
						<p className="text-xs text-red-400 mt-0.5">{String(error)}</p>
					</div>
					<button
						onClick={() => refetch()}
						className="px-3 py-1.5 text-xs rounded bg-red-700 hover:bg-red-600 text-white transition-colors shrink-0"
					>
						Retry
					</button>
				</div>
			</div>
		);
	}

	// Empty state — should not normally trigger since we have defaults
	if (!preferences) {
		return (
			<div className={`space-y-4 ${className ?? ""}`}>
				<div className="flex flex-col items-center justify-center py-12 text-stone-400 dark:text-stone-500">
					<BellOff size={24} className="mb-2" />
					<p className="text-sm">No notification preferences found.</p>
					<button
						onClick={() => refetch()}
						className="mt-3 px-3 py-1.5 text-xs rounded bg-stone-100 dark:bg-[#2A2A2A] hover:bg-stone-200 dark:hover:bg-[#333] text-stone-700 dark:text-stone-300 transition-colors"
					>
						Refresh
					</button>
				</div>
			</div>
		);
	}

	// ── Main form ────────────────────────────────────────────────────

	const allTypes = Object.keys(NOTIFICATION_TYPE_LABELS) as NotificationType[];

	return (
		<div className={`space-y-4 ${className ?? ""}`}>
			<p className="text-xs text-stone-400 dark:text-stone-500 mb-3">
				Configure how and when you receive notifications from Pi.
			</p>

			{/* Global enable */}
			<div className="flex items-center gap-3 pb-3 border-b border-[#E8E6E1] dark:border-[#333]">
				<Bell size={16} className="text-stone-500 dark:text-stone-400 shrink-0" />
				<div className="flex-1 min-w-0">
					<span className="text-sm font-medium text-stone-800 dark:text-stone-200">Enable Notifications</span>
					<p className="text-xs text-stone-400 dark:text-stone-500">
						Master switch — when disabled, no notifications are sent
					</p>
				</div>
				<Toggle enabled={enabled} onToggle={() => setEnabled(!enabled)} />
			</div>

			{/* Channel settings */}
			<div className={enabled ? "" : "opacity-40 pointer-events-none"}>
				<h4 className={`text-xs uppercase tracking-widest font-semibold mb-1 text-stone-400 dark:text-stone-500`}>
					Delivery Channels
				</h4>
				<div className="divide-y divide-[#E8E6E1] dark:divide-[#333]">
					{channels.length === 0 ? (
						<p className="text-xs text-stone-400 dark:text-stone-500 py-2">No channels available.</p>
					) : (
						channels.map((ch) => (
							<ChannelRow
								key={ch.channel}
								channel={ch.channel}
								enabled={channelStates[ch.channel] ?? false}
								configured={ch.configured}
								onToggle={() => handleChannelToggle(ch.channel)}
							/>
						))
					)}
				</div>

				{/* Email not configured notice */}
				{channelStates.email && channels.find((c) => c.channel === "email" && !c.configured) && (
					<div className="flex items-start gap-2 mt-2 p-2 rounded bg-yellow-900/10 border border-yellow-900/30">
						<AlertTriangle size={12} className="text-yellow-400 shrink-0 mt-0.5" />
						<p className="text-xs text-yellow-300">
							Email channel is enabled but not configured. Configure SMTP settings to enable email delivery.
						</p>
					</div>
				)}

				{/* Per-type routing rules */}
				<div className="mt-4">
					<h4 className={`text-xs uppercase tracking-widest font-semibold mb-1 text-stone-400 dark:text-stone-500`}>
						Per-Type Routing
					</h4>
					<p className="text-xs text-stone-400 dark:text-stone-500 mb-2">
						Control which channels each notification type is delivered through.
						Uncheck a channel to mute that type for that channel.
					</p>
					<div className="divide-y divide-[#E8E6E1] dark:divide-[#333] border border-[#E8E6E1] dark:border-[#333] rounded p-3 bg-white dark:bg-[#1E1E1E]/20 max-h-64 overflow-y-auto">
						{allTypes.map((type) => (
							<TypeRuleRow
								key={type}
								type={type}
								rules={typeRules[type] ?? {}}
								onRuleChange={handleRuleChange}
							/>
						))}
					</div>
				</div>
			</div>

			{/* Save / Reset */}
			<div className="flex items-center justify-between pt-2 border-t border-[#E8E6E1] dark:border-[#333]">
				<div className="flex items-center gap-2">
					{isDirty && (
						<span className="text-xs text-yellow-500">Unsaved changes</span>
					)}
					{saved && (
						<span className="flex items-center gap-1 text-xs text-green-400">
							<CheckCircle size={12} />
							Saved
						</span>
					)}
				</div>
				<div className="flex items-center gap-2">
					<button
						onClick={handleReset}
						disabled={isSaving}
						className="flex items-center gap-1 px-2.5 py-1.5 text-xs rounded bg-stone-100 dark:bg-[#2A2A2A] hover:bg-stone-200 dark:hover:bg-[#333] text-stone-700 dark:text-stone-300 disabled:opacity-40 transition-colors"
					>
						<RotateCcw size={12} />
						Reset
					</button>
					<button
						onClick={handleSave}
						disabled={isSaving || !isDirty}
						className={`px-4 py-2 text-xs rounded transition-colors disabled:opacity-40 ${
							isDirty
								? "bg-blue-700 hover:bg-blue-600 text-white"
								: "bg-stone-100 dark:bg-[#2A2A2A] text-stone-400 dark:text-stone-500 cursor-not-allowed"
						}`}
					>
						{isSaving ? "Saving..." : isDirty ? "Save" : "No changes"}
					</button>
				</div>
			</div>
		</div>
	);
}
