/**
 * PlanSpec v5 Alpha2 Types — Zod-inferred types (GENERATED)
 *
 * DO NOT EDIT THIS FILE BY HAND.
 * The type definitions are derived automatically from the Zod schema
 * in alpha2-schema.ts.
 *
 * Regenerate the schema by running:
 *   tsx packages/coding-agent/scripts/generate-plan-template.ts
 */

import type { z } from "zod";
import type { PlanSpecV5Alpha2Schema } from "./plan-compiler/alpha2/alpha2-schema.js";

export type PlanSpecV5Alpha2 = z.infer<typeof PlanSpecV5Alpha2Schema>;
